import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Batalha-Naval-A3-EM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <h1>Sistema : Menu</h1>
          <nav>
            <ul>
              <li>
                <Link href= "/">Home</Link>
              </li>
              <li>
                <Link href= "/login">Login</Link>
                </li>
              <li>
                <Link href= "/registro">Registro</Link>
                </li>
              <li>
                <Link href= "/jogadorlista">Lista de Jogadores</Link>
                </li>
            </ul>
          </nav>
          <hr />
        {children}
      </body>
    </html>
  );
}
